// <auto-generated />
using DreamGarage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamGarage.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DreamGarage.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<bool>("IsElectric")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHybrid")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Trim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Orange",
                            Horsepower = 710,
                            IsElectric = false,
                            IsHybrid = false,
                            Make = "McLaren",
                            Model = "720S",
                            Price = 275000,
                            Trim = "Performance",
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            Horsepower = 580,
                            IsElectric = false,
                            IsHybrid = false,
                            Make = "Porsche",
                            Model = "911",
                            Price = 200000,
                            Trim = "Turbo S",
                            Year = 2018
                        },
                        new
                        {
                            Id = 3,
                            Color = "Lime",
                            Horsepower = 759,
                            IsElectric = false,
                            IsHybrid = false,
                            Make = "Lamborghini",
                            Model = "Aventador",
                            Price = 550000,
                            Trim = "SVJ",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Color = "Blue",
                            Horsepower = 627,
                            IsElectric = false,
                            IsHybrid = false,
                            Make = "BMW",
                            Model = "M5",
                            Price = 145000,
                            Trim = "CS",
                            Year = 2021
                        },
                        new
                        {
                            Id = 5,
                            Color = "Red",
                            Horsepower = 631,
                            IsElectric = false,
                            IsHybrid = true,
                            Make = "Audi",
                            Model = "RS Q8",
                            Price = 135000,
                            Trim = "Performance",
                            Year = 2025
                        },
                        new
                        {
                            Id = 6,
                            Color = "Silver",
                            Horsepower = 2107,
                            IsElectric = true,
                            IsHybrid = false,
                            Make = "Rimac",
                            Model = "Nevera",
                            Price = 2500000,
                            Trim = "R",
                            Year = 2024
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
